text = int(input("Please tell me your age: "))
print(f"You are currently {text} years old.")
print(f"In 10 years, you'll be {text + 10} years old.")
print(f"In 20 years, you'll be {text + 20} years old.")
print(f"In 30 years, you'll be {text + 30} years old.")
